[[games]]
name = "DELTARUNE gaming"
launch_command = "survey_program"
description = "deltarune gaming"

[[games]]
name = "risk of rain 2"
launch_command = "gaming"
description = "i fucking love risky rain"

[[games]]
name = "rorrr"
launch_command = "gaming"
description = "Risk of Rain Returns 2 the second: new and improved"

[[games]]
name = " dsflsdf ğŸ¸ï¸ kjsdnf ğŸš€ï¸"
launch_command = "k hfsdfh dsfjsdjf "
description = "gaming"
